config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :raids do
    get :autocomplete_raid_location, :on => :collection

  end
  root 'welcome#index'

end

app/models/raid.rb
class Raid < ActiveRecord::Base

  scope :uniquely_placed, -> {  group(:location) }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/raids_controller.rb
class RaidsController < ApplicationController
  autocomplete :raid, :location, :scopes => [:uniquely_placed]
  skip_before_action :authenticate_user!, only: [:index, :autocomplete_raid_location]

  before_action :set_raid, only: [:show, :edit, :update, :destroy]

  def index
    @raids = Raid.all
    if params[:search]
      @raids = Raid.where('location like ?', "%#{params[:search]}%")
    end
  end

  def show
  end

  def new
    @raid = Raid.new
  end

  def edit
  end

  def create
    @raid = Raid.new(raid_params)

    respond_to do |format|
      if @raid.save
        format.html { redirect_to @raid, notice: 'Raid was successfully created.' }
        format.json { render :show, status: :created, location: @raid }
      else
        format.html { render :new }
        format.json { render json: @raid.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @raid.update(raid_params)
        format.html { redirect_to @raid, notice: 'Raid was successfully updated.' }
        format.json { render :show, status: :ok, location: @raid }
      else
        format.html { render :edit }
        format.json { render json: @raid.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @raid.destroy
    respond_to do |format|
      format.html { redirect_to raids_url, notice: 'Raid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_raid
    @raid = Raid.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def raid_params
    params.require(:raid).permit(:event_date, :location, :dead_civilian, :race, :dead_officer_1, :dead_officer_2, :standard_warrant, :no_knock_warrant, :warrant_type_unknown, :video, :source)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/raids_helper.rb
module RaidsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title= content_for?(:title) ? yield(:title) : "StackOverflow Answers Code: Devise + Autocomplete"
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Devise + Autocomplete'}"}
    = csrf_meta_tags
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "all,follow", :name => "robots"}/
    %meta{:content => "index,follow,snippet,archive", :name => "googlebot"}/
    %meta{:content => "", :name => "keywords"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Montserrat:400,700|Merriweather:400,400italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "favicon.png", :rel => "shortcut icon"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    %meta{:content => "deals, specials, on sale, buying admin, group buying, group deals, local specials", :name => "keywords"}/
    / =============== APP STYLES ===============
    = stylesheet_link_tag 'application', media: 'all', id: "maincss"
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", media: "all"
    / =============== VIEW VENDOR STYLES ===============
    = stylesheet_link_tag params[:controller]
    :css
      #content > #right > .dose > .dosesingle,
      #content > #center > .dose > .dosesingle
      {display:none !important;}
  %body{class: "#{params[:controller]}-#{params[:action]}"}
    .site-wrapper
      .site-wrapper-inner
        .cover-container
          #notifications
            = render '/layouts/messages'
          = yield
        / Page footer
    / =============== VENDOR SCRIPTS ===============
    = javascript_include_tag 'application'
    / =============== VIEW VENDOR SCRIPTS ===============
    = javascript_include_tag params[:controller]
    / =============== APP SCRIPTS ===============
    = javascript_include_tag 'application'
    %script{:crossorigin => "anonymous", :integrity => "sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb", :src => "https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"}
    = yield :body_area
    = yield :footer_scripts

app/views/layouts/page_partials/_footer.html.haml
%span © #{Date.today.year} - Hello Crowd Inc

app/views/raids/_form.html.haml
= form_for(@raid) do |f|
  - if @raid.errors.any?
    #error_explanation
      %h2
        = pluralize(@raid.errors.count, "error")
        prohibited this raid from being saved:
      %ul
        - @raid.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :event_date
    %br/
    = f.date_select :event_date
  .field
    = f.label :location
    %br/
    = f.text_field :location
  .field
    = f.label :dead_civilian
    %br/
    = f.text_field :dead_civilian
  .field
    = f.label :race
    %br/
    = f.text_field :race
  .field
    = f.label :dead_officer_1
    %br/
    = f.text_field :dead_officer_1
  .field
    = f.label :dead_officer_2
    %br/
    = f.text_field :dead_officer_2
  .field
    = f.label :standard_warrant
    %br/
    = f.check_box :standard_warrant
  .field
    = f.label :no_knock_warrant
    %br/
    = f.check_box :no_knock_warrant
  .field
    = f.label :warrant_type_unknown
    %br/
    = f.check_box :warrant_type_unknown
  .field
    = f.label :video
    %br/
    = f.text_field :video
  .field
    = f.label :source
    %br/
    = f.text_field :source
  .actions
    = f.submit

app/views/raids/edit.html.haml
%h1 Editing Raid
= render 'form'
= link_to 'Show', @raid
|
= link_to 'Back', raids_path

app/views/raids/index.html.haml
.row
  .col-md-6
    %h1 All Raids
  .col-md-6
    = form_tag raids_path, class: "form-inline", method: :get do
      .input-group
        = text_field_tag :search, params[:search], class: "form-control", :placeholder => "Location Search", data: { autocomplete: autocomplete_raid_location_raids_path }
        %span.input-group-btn
          %button.btn.btn-secondary{:type => "submit"}
            %span.fa.fa-search
.row
  .col-md-12
    %table.table.table-striped
      %thead
        %tr
          %th Event date
          %th Location
          %th Dead civilian
          %th Race
          %th Dead officer
          %th Dead officer
          %th Standard warrant
          %th No knock warrant
          %th Warrant type unknown
          %th Video
          %th Source
          %th Actions
      %tbody
        - @raids.each do |raid|
          %tr
            %td= raid.event_date
            %td= raid.location
            %td= raid.dead_civilian
            %td= raid.race
            %td= raid.dead_officer_1
            %td= raid.dead_officer_2
            %td= raid.standard_warrant
            %td= raid.no_knock_warrant
            %td= raid.warrant_type_unknown
            - if raid.video
              %td= link_to "Video", raid.video
            - else
              %td N/A
            - if raid.source
              %td= link_to "Original News Story", raid.source
            - else
              %td N/A
            %td.btns-actions
              = link_to raid, class: "btn btn-default btn-xs" do
                %span.fa.fa-eye.text-primary
              = link_to edit_raid_path(raid), class: "btn btn-default btn-xs" do
                %span.fa.fa-pencil.text-success
              = link_to raid, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs" do
                %span.fa.fa-trash.text-danger
  %br/

.row
  .col-md-6
    = link_to 'New Raid', new_raid_path


:css 
  table.table .btn-default { border: 1px solid #777; }
  .btns-actions .btn{ display: inline-block;  }
  .btns-actions { min-width: 90px; }
  ul#ui-id-1.ui-menu.ui-widget.ui-widget-content.ui-autocomplete.ui-front { max-width: 300px; background: #f1f1f1; border: 1px solid; }
  .ui-menu-item-wrapper { color: #888; text-shadow: none;}
  table.table > tbody td a { color: #777;}

app/views/raids/new.html.haml
%h1 New Raid
= render 'form'
= link_to 'Back', raids_path

app/views/raids/show.html.haml
%p#notice= notice
%p
  %strong Event date:
  = @raid.event_date
%p
  %strong Location:
  = @raid.location
%p
  %strong Dead civilian:
  = @raid.dead_civilian
%p
  %strong Race:
  = @raid.race
%p
  %strong Dead officer 1:
  = @raid.dead_officer_1
%p
  %strong Dead officer 2:
  = @raid.dead_officer_2
%p
  %strong Standard warrant:
  = @raid.standard_warrant
%p
  %strong No knock warrant:
  = @raid.no_knock_warrant
%p
  %strong Warrant type unknown:
  = @raid.warrant_type_unknown
%p
  %strong Video:
  = @raid.video
%p
  %strong Source:
  = @raid.source
= link_to 'Edit', edit_raid_path(@raid)
|
= link_to 'Back', raids_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/welcome/index.html.haml
.masthead.clearfix
  .inner
.inner.cover
  %h1.cover-heading StackOverflow Code Examples
  %p.lead Illustrating the point is so much easier than attempting to use theoretical explanations.
  %p.lead
    %a.btn.btn-lg.btn-secondary{:href => "http://stackoverflow.com/users/1753596/trh"} My Stack Oveflow
  %p.lead
    %a{href: "http://stackoverflow.com/questions/43007120/rails-4-autocomplete-and-devise-authorization"}
      Question
  %p.lead
    = link_to "Code Answer", raids_path
.mastfoot
  .inner
    %p
      Stack Overflow Answers Code found @
      = succeed "," do
        %a{:href => "https://bitbucket.org/bunglify/"} Bunglify Bitbucket
      = succeed "." do
        %a{:href => "https://twitter.com/Bunglify"} @Bunglify